# Generated by Django 4.2.6 on 2023-11-13 01:42

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.CharField(max_length=255, verbose_name='Hona')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hona', to='apps.floor', verbose_name='etaj')),
            ],
            options={
                'verbose_name': 'Honalar',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=125, verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Guruhlar',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Universitet Nomi')),
            ],
            options={
                'verbose_name': 'Univeristet',
            },
        ),
        migrations.CreateModel(
            name='TTJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='TTJ nomi')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttj_university', to='apps.university')),
            ],
            options={
                'verbose_name': 'TTJ',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_floor', to='apps.floor', verbose_name='Hona')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to='apps.group', verbose_name='Student Group')),
                ('ttj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ttj', to='apps.ttj', verbose_name='TTJ')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_university', to='apps.university', verbose_name='Universitet')),
            ],
            options={
                'verbose_name': 'Studentlar',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('on_ttj', models.BooleanField(default=False, verbose_name='yotoqhonada')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendace_student', to='apps.student', verbose_name='Students')),
            ],
            options={
                'verbose_name': 'Yoqlama',
            },
        ),
    ]
